### ISSUE TITLE
I was pleased to see this project

### ISSUE THREAD

**Issue by joncrlsn** [PetrGlad/python-prevayler#13]
Hi, I'm sorry this isn't an "issue".  Let me know if there is a more appropriate place to post.  

I just wanted to tell you that I was very pleased to see this project.  I'm a Java developer and a fan of Prevayler... but I'm finding that I'd like to do some personal projects with Python... and possibly Django.

I like the simplicity of Prevayler and this project seems to fit in with that... not too much framework code and easy to use.

What kind of projects have you used this on and are you still using it?  I'd like to create a relational web tool, but I don't want to store the query data in a relational database.  Prevayler seems more appropriate to me.

Thanks!

**Comment by PetrGlad** [comment]
This was more of an exercise - the whole code took several hours to write. I was fascinated by Prevayler and wanted it for one of my projects at work but for several reasons usual RDBMS was chosen instead.
No, I have not used it for any production code, but if you think that all data can fit into memory I think it is worth trying.

**Comment by joncrlsn** [comment]
Thanks for the response.  I started trying it out more last night.  I come from a Java background and am still not very familiar with the Python threading model.  I noticed that it doesn't clean up old log files and it should probably lock during queries (not real performant, I know).  I know Java throws errors if you change a map or list while iterating through it but maybe it's not such a problem with Python.

**Comment by PetrGlad** [comment]
I think you may well ask python specific questions on python mailing lists, they were responsive for me in the past. 

Threads in Prevayler are usually not an issue since your transactions are applied in single thread - this helps to reduce synchronization complexity but may also be a limitation in some cases.

You may also have look at  Jython (which is based on JVM and hence does not have GIL https://wiki.python.org/moin/GlobalInterpreterLock) or at my recent favorite, Clojure. One of biggest strengths of Clojure is immutabe data structures that are of great help in many situations.
